services:
  frontend:
    build: ./frontend
    ports: 
      - 8080:80
    depends_on:
      - backend
  backend:
    build: ./backend
    ports: 
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tododb
      POSTGRES_USER: root
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

